command: [
  "uvicorn",
  "app:app"
]

env:
  - name: 'MLFLOW_TRACKING_URI'
    value: 'databricks'
  - name: 'MLFLOW_EXPERIMENT_ID'
    value: '380962412407109'
  - name: 'LLM_MODEL'
    value: 'agents-demo-gpt4o'
  - name: 'VITE_DATABRICKS_HOST'
    value: 'https://e2-demo-west.cloud.databricks.com'
  - name: 'VITE_MLFLOW_EXPERIMENT_ID'
    value: '380962412407109'
  - name: 'BACKEND_URL'
    value: 'https://genai-email-demo-2556758628403379.aws.databricksapps.com'
  - name: 'LAKEHOUSE_APP_NAME'
    value: 'genai-email-demo'
  - name: 'APP_FOLDER_IN_WORKSPACE'
    value: '/Workspace/Users/eric.peter@databricks.com/genai-email-demo'
  - name: 'GIT_COMMIT_HASH'
    value: 'ece0c6b69e175a3998b73e6c21ab398f-dirty-31b336e8'
