command: [
  "uvicorn",
  "app:app"
]

env:
  - name: 'MLFLOW_EXPERIMENT_ID'
    value: '380962412404969'
  - name: 'LLM_MODEL'
    value: 'ep-gpt4o-new'
  - name: 'VITE_DATABRICKS_HOST'
    value: 'https://e2-demo-west.cloud.databricks.com'
  - name: 'VITE_MLFLOW_EXPERIMENT_ID'
    value: '380962412404969'
