command: [
  "uvicorn",
  "app:app"
]

env:
  - name: 'MLFLOW_TRACKING_URI'
    value: 'databricks'
  - name: 'MLFLOW_EXPERIMENT_ID'
    value: '380962412404969'
  - name: 'LLM_MODEL'
    value: 'agents-demo-gpt4o'
  - name: 'VITE_DATABRICKS_HOST'
    value: 'https://e2-demo-west.cloud.databricks.com'
  - name: 'VITE_MLFLOW_EXPERIMENT_ID'
    value: '380962412404969'
  - name: 'BACKEND_URL'
    value: 'https://genai-email-demo-2556758628403379.aws.databricksapps.com'
